"""
Auto-generated by core/recheck.py to surgically heal identified faulty pages.
Target Database: nextjs-search-app/data/voters.db
"""
import os
import sys
from pypdf import PdfReader, PdfWriter
from pathlib import Path

# Core modules
from extractor import extract_from_chunk, clean_voter_record
from database import get_connection
from google import genai
import google.auth
from google.auth.exceptions import DefaultCredentialsError

TARGET_PAGES = {'input_pdfs\\Ward No-004-Part No-001.pdf': {'ward': 4, 'pages': [3, 5, 6, 7, 10, 11, 12, 13, 14, 17, 22, 23, 24, 25, 26, 27, 31, 32, 35, 38, 39, 40, 41, 42, 43, 44, 46, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57]}}

def rescan_and_heal():
    print("=" * 60)
    print("🚑 HEALING FAULTY PAGES (High-Precision Single-Page Extractor)")
    print("=" * 60)

    try:
        credentials, project_id = google.auth.default()
        client = genai.Client(vertexai=True, project=project_id, location='us-central1')
        print(f"Authenticated with Vertex AI. Project: {project_id}")
    except DefaultCredentialsError:
        print("❌ Error: GCP credentials not found. Run: gcloud auth application-default login")
        return

    base_dir = os.path.dirname(os.path.dirname(__file__))
    temp_dir = Path(base_dir) / "temp_pages"
    temp_dir.mkdir(exist_ok=True)

    total_healed = 0

    for pdf_rel_path, target_info in TARGET_PAGES.items():
        pdf_full_path = os.path.join(base_dir, pdf_rel_path)
        ward = target_info['ward']
        pages = target_info['pages']
        source_filename = os.path.basename(pdf_full_path)

        if not os.path.exists(pdf_full_path):
            print(f"⚠️ PDF not found: {pdf_full_path}. Skipping.")
            continue

        reader = PdfReader(pdf_full_path)
        print(f"\n📄 Rescanning {len(pages)} faulty page(s) in {source_filename} (Ward {ward}): {pages}")

        for page_num in pages:
            if page_num < 1 or page_num > len(reader.pages):
                continue

            page = reader.pages[page_num - 1]
            writer = PdfWriter()
            writer.add_page(page)

            temp_pdf = temp_dir / f"heal_w{ward}_p{page_num}.pdf"
            with open(temp_pdf, "wb") as f:
                writer.write(f)

            try:
                raw_voters = extract_from_chunk(client, str(temp_pdf), page_num, page_num)
                valid_voters = []
                for raw in raw_voters:
                    cleaned = clean_voter_record(raw, page_num, ward, source_filename)
                    if not cleaned['is_deleted_or_shifted']:
                        valid_voters.append(cleaned)

                with get_connection() as conn:
                    cur = conn.cursor()
                    cur.execute("DELETE FROM voters WHERE ward = ? AND page_number = ?", (ward, page_num))
                    for v in valid_voters:
                        cur.execute("""
                            INSERT OR REPLACE INTO voters 
                            (ward, serial_number, voter_id, name_hi, relative_name_hi, relative_type, house_number, age, gender, page_number, source_file)
                            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                        """, (
                            v['ward'], v['serial_number'], v['voter_id'], v['name_hi'],
                            v['relative_name_hi'], v['relative_type'], v['house_number'],
                            v['age'], v['gender'], v['page_number'], v['source_file']
                        ))
                    conn.commit()

                print(f"  ✅ Page {page_num}: Successfully updated with {len(valid_voters)} clean voters.")
                total_healed += len(valid_voters)

            except Exception as e:
                print(f"  ❌ Error healing Page {page_num}: {e}")
            finally:
                if temp_pdf.exists():
                    temp_pdf.unlink()

    try:
        temp_dir.rmdir()
    except OSError:
        pass

    print(f"\n🎉 Healing complete! Total records updated: {total_healed}")
    print("Run 'python core/recheck.py' again to verify 99%+ accuracy score.")

if __name__ == "__main__":
    rescan_and_heal()
